(deftheme jml-jedit-retro
  "Created 2012-08-19.")

(custom-theme-set-variables
 'jml-jedit-retro
 '(Buffer-menu-use-header-line nil)
 '(TeX-shell "bash")
 '(auto-save-list-file-prefix "~/.emacs.d/auto-save-list/.saves-")
 '(backup-by-copying-when-linked t)
 '(c-default-style "java")
 '(case-fold-search t)
 '(compilation-mode-hook (quote ((lambda nil (toggle-truncate-lines nil)))))
 '(compilation-scroll-output t)
 '(current-language-environment "English")
 '(custom-buffer-indent 4)
 '(desktop-base-file-name ".emacs.d/.emacs.desktop")
 '(desktop-base-lock-name ".emacs.d/.emacs.desktop.lock")
 '(exec-path (quote ("/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Applications/Emacs.app/Contents/MacOS/bin" "/usr/local/bin")))
 '(find-file-existing-other-name nil)
 '(flymake-log-level -1)
 '(grep-template "grep <C> -I -nH -e <R> <F>")
 '(indent-tabs-mode nil)
 '(initial-major-mode (quote text-mode))
 '(initial-scratch-message nil)
 '(kill-whole-line nil)
 '(mail-envelope-from (quote header))
 '(mail-specify-envelope-from t)
 '(org-agenda-custom-commands (quote (("n" "Agenda and all TODO's" ((agenda "") (alltodo))) ("w" "Waiting For" todo "WF") ("i" "In progress" todo "INPROGRESS"))))
 '(org-agenda-dim-blocked-tasks (quote invisible))
 '(org-agenda-files (quote ("~/Dropbox/Organize/ACTIONS")))
 '(org-completion-use-iswitchb t)
 '(org-enforce-todo-dependencies t)
 '(org-fontify-done-headline t)
 '(org-fontify-whole-heading-line t)
 '(org-hide-leading-stars t)
 '(org-link-abbrev-alist (quote (("lp" . "https://bugs.launchpad.net/bugs/") ("RT" . "https://rt.admin.canonical.com/Ticket/Display.html?id="))))
 '(org-link-frame-setup (quote ((vm . vm-visit-folder-other-frame) (gnus . org-gnus-no-new-news) (file . find-file) (wl . wl-other-frame))))
 '(org-modules (quote (org-bbdb org-bibtex org-docview org-gnus org-info org-jsinfo org-irc org-mew org-mhe org-rmail org-vm org-wl org-w3m)))
 '(org-startup-indented t)
 '(org-stuck-projects (quote ("/-DONE" ("TODO" "AGENDA") nil "")))
 '(org-todo-keywords (quote ((sequence "TODO" "INPROGRESS" "|" "WF" "DONE" "CANCELLED") (sequence))))
 '(org-use-fast-todo-selection t)
 '(package-archives (quote (("marmalade" . "http://marmalade-repo.org/packages/") ("gnu" . "http://elpa.gnu.org/packages/"))))
 '(pop-up-windows nil)
 '(query-user-mail-address nil)
 '(require-final-newline t)
 '(safe-local-variable-values (quote ((test-case-name . twisted\.trial\.test\.test_runner) (encoding . utf8) (encoding . utf-8))))
 '(scroll-bar-mode nil)
 '(scroll-conservatively 100000)
 '(scroll-down-aggressively nil)
 '(scroll-step 0)
 '(scroll-up-aggressively nil)
 '(sendmail-program "/usr/bin/msmtp")
 '(sentence-end-double-space t)
 '(shell-file-name "/bin/bash")
 '(show-paren-style (quote expression))
 '(show-trailing-whitespace t)
 '(split-height-threshold nil)
 '(split-width-threshold nil)
 '(tab-width 4)
 '(tex-shell-file-name nil)
 '(text-mode-hook (quote (turn-on-auto-fill text-mode-hook-identify)))
 '(track-eol t)
 '(truncate-lines t)
 '(user-mail-address "jml@mumak.net")
 '(vc-handled-backends (quote (RCS CVS SVN SCCS Git Hg Arch)))
 '(vc-make-backup-files t)
 '(visible-bell t)
 '(x-select-enable-clipboard t)
 '(which-function-mode t)
 '(uniquify-buffer-name-style (quote post-forward-angle-brackets))
 '(transient-mark-mode t)
 '(tool-bar-mode nil)
 '(show-paren-mode t)
 '(menu-bar-mode nil)
 '(line-number-mode t)
 '(global-font-lock-mode t)
 '(desktop-save-mode t)
 '(column-number-mode t)
 '(blink-cursor-mode nil))

(custom-theme-set-faces
 'jml-jedit-retro
 '(default ((t (:stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :family "Ubuntu Mono"))))
 '(dired-directory ((t (:foreground "blue" :weight bold))))
 '(flymake-errline ((((class color) (background light)) (:underline "red"))))
 '(font-lock-builtin-face ((((class color) (min-colors 88) (background light)) (:foreground "darkred" :weight bold))))
 '(font-lock-comment-face ((((class color) (min-colors 88) (background light)) (:foreground "#007070" :slant italic))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-function-name-face ((((class color) (min-colors 88) (background light)) (:foreground "blue" :weight bold))))
 '(font-lock-keyword-face ((((class color) (min-colors 88) (background light)) (:weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 88) (background light)) (:foreground "#007070"))))
 '(font-lock-type-face ((((class color) (min-colors 88) (background light)) (:foreground "red" :weight bold))))
 '(font-lock-variable-name-face ((((class color) (min-colors 88) (background light)) (:foreground "red"))))
 '(font-lock-warning-face ((((class color) (min-colors 88) (background light)) (:background "red"))))
 '(org-headline-done ((((class color) (min-colors 16) (background light)) (:foreground "ForestGreen" :strike-through t))))
 '(org-level-1 ((((class color) (background light)) (:weight bold :height 1.5))))
 '(org-level-2 ((((class color) (background light)) nil)))
 '(org-level-3 ((((class color) (background light)) nil))))

(provide-theme 'jml-jedit-retro)
